### ISSUE TITLE
Documentation for June release

### ISSUE THREAD

**Issue by ksbeattie** [nawi-hub/proteuslib#113]
- [x] Welcome/overview page (@TimBartholomew) (#127)
- [x] #145
- [x] Background (@TimBartholomew) (#124)
- [x] How-to on Chemistry (@aladshaw3) (#129)
- [x] Parameter Sweep tool (@eyoung55) (#123)
- [x] Electrolyte DB (@dangunter) (#77)
- [x] Jupyter Notebook with simple RO model (@bknueven, @lbianchi-lbl, @adam-a-a) (#117)
