### ISSUE TITLE
Master issue: 1D-RO implementation

### ISSUE THREAD

**Issue by adam-a-a** [nawi-hub/proteuslib#126]
We need a 1D implementation of the RO model. 

First approach: 

- Implement 1D control volumes for feed and permeate sides of membrane
- don't add material, energy, momentum balances for the permeate (assuming this will eliminate effects of flow directionality on the permeate side)
- Start with simplified RO case; i.e., no concentration polarization, no pressure drop.

**Task list:**

- [x] Add config options to unit model class
- [x] Add `build` method to unit model class
- [x] Add `_make_performance `method to unit model class (containing variables and constraints)
- [x] Add `initialize `method to unit model class
- [x] Add `calculate_scaling_factors `method to unit model class
- [x] Create tests for unit model
- [x] Reiterate all steps until working version complete
- [x] Add/revise `get_costing `method as needed
- [x] Add `_get_performance_contents `for `report()` method
- [x] Add `_get_stream_table `for `report()` method

EDIT: Per @andrewlee94's recommendation, and because I was having trouble with my initial attempt, I switched the approach from using 1d control volumes for both sides of the membrane to just having a 1d CV for the feed side and an indexed stateblock for the permeate side (with one more stateblock for the final permeate at the module outlet).

**Comment by adam-a-a** [comment]
@andrewlee94 I might have to ping you soon to chat about developing 1D models with IDAES, when you have the time. For now, I'm taking a first shot at developing the 1DRO model by following some of the 1D models in the idaes-pse repo. 

To give an initial idea of the approach, I am setting up the feed-side of the membrane and the permeate-side of the membrane each as a 1D control volume, but the permeate side should have no directional flow (only mass transfer from feed side at each finite element). At the moment, one thing that I'm unsure about is whether I need to (and how to) multiply the `mass_transfer_term` by dx since it seems that the mass transfer term (and most other terms from the 1D CV) are per unit length. Looking at other 1D models, this wasn't clear to me.

**Comment by andrewlee94** [comment]
First of all, I don't know if you need a 1-D control volume for the permeate flow.
Secondly, yes, the mass transfer will need to be multiplied by dx as it is per unit length.

**Comment by adam-a-a** [comment]
> First of all, I don't know if you need a 1-D control volume for the permeate flow.
> 
> Secondly, yes, the mass transfer will need to be multiplied by dx as it is per unit length.

I agree- we don't need a 1D control volume for the permeate side just yet, but we were thinking that a future counter-flow module, where the permeate side does have directional flow parallel to the membrane, could inherit this RO model. Essentially, we're thinking to keep the same structure between models.

**Comment by andrewlee94** [comment]
I would leave that discussion for another time and just make something that works here for now. My initial feeling is that there would be enough structural differences between this and the counter-flow model that it would not be worth trying to inherit.

**Comment by adam-a-a** [comment]
An alternative that I was thinking of was to have the feed side as a 1D control volume and the permeate side as a mixer, where mass transfer per length element from the feed side is connected to its own inlet on a mixer. The mixer outlet would give the final permeate concentration and flow rate. Am I overcomplicating this?

**Comment by andrewlee94** [comment]
I think a Mixer unit model is definitely over-complicating this. I would be inclined to have the permeate side be a single StateBlock, with a set of custom material and energy balances to calculate the flow terms.

**Comment by adam-a-a** [comment]
I assumed that we'd need a stateblock for each finite element since we need to the concentration and osmotic pressure along the length of the permeate channel.

**Comment by andrewlee94** [comment]
If you are allowing the concentration of the permeate side to vary as a function of length, then yes you would need multiple StateBlocks (plus another one for the aggregate outlet).

In earlier discussions with @TimBartholomew we were working on the basis of a single, uniform permeate side.

**Comment by TimBartholomew** [comment]
> If you are allowing the concentration of the permeate side to vary as a function of length, then yes you would need multiple StateBlocks (plus another one for the aggregate outlet).
> 
> In earlier discussions with @TimBartholomew we were working on the basis of a single, uniform permeate side.

@andrewlee94 yeah we were working from one uniform permeate side initially, but I recently just updated the 0D RO model to have separate permeate blocks for the inlet and outlet because one uniform permeate had unintended effects for low salt rejection RO.

**Comment by andrewlee94** [comment]
So, this one will be fun then. First, look at the BFB and MB bed models in IDAES: https://github.com/IDAES/idaes-pse/tree/main/idaes/gas_solid_contactors/unit_models

You will need to define the length domain at the unit model level, and pass that to the retentate control volume.
For the permeate side, I would suggest a set of indexed StateBlocks to represent the properties at each point, and a final permeate output block which sums up the flow contributions.

**Comment by adam-a-a** [comment]
> So, this one will be fun then. First, look at the BFB and MB bed models in IDAES: https://github.com/IDAES/idaes-pse/tree/main/idaes/gas_solid_contactors/unit_models
> 
> You will need to define the length domain at the unit model level, and pass that to the retentate control volume.
> For the permeate side, I would suggest a set of indexed StateBlocks to represent the properties at each point, and a final permeate output block which sums up the flow contributions.

@andrewlee94 I still need to check out the links you provided (think I already skimmed through the BFB previously), but couldn't I achieve that set of indexed StateBlocks by using a 1D control volume without defining inlet/outlets and omitting material, energy, momentum balance methods (e.g., `add_material_balance(...)`? Here's what I have so far: #137

**Comment by andrewlee94** [comment]
@adam-a-a You could, but that the control volume adds a lot of stuff you don't need.
