### ISSUE TITLE
Master Issue: Full Treatment Train Flowsheets

### ISSUE THREAD

**Issue by adam-a-a** [nawi-hub/proteuslib#181]
We need full treatment trains for BW and SW feeds:
- [x] Translator block constraints between NaCl-CaSO4-H2O -->NaCl (and/or seawater prop model) (@adam-a-a )
- [x] Connect NaCl-CaSO4-H2O w/0-order NF to 0D RO system (w/pump but not necessarily ERD) (@adam-a-a )
- [x] Add initial constraint@ outlet of RO, roughly related to CaSO4 concentration at outlet of ND divided by (1-R) (probably can do CaSO4 mass flowrate out of NF / total mass flowrate out of RO) (@adam-a-a)
- [x] swap 0DRO with 1D RO (@adam-a-a)
- [x] Translator block TDS to gen chem property package for chlorination (@srikanthallu , @aladshaw3) 
- [x] add chlorination step for post-treatment to 0 order RO on flowsheet (@aladshaw3, @srikanthallu)
- [x] develop 0-order NF based on DSPM-DE data (@TimBartholomew) 
- [x] replace 0-order separator with 0-order NF (based on DPSM-DE data) on the NF-0dRO sub-flowsheet (@TimBartholomew) 
- [x] connect chlorination step to 0D RO on flowsheet (@aladshaw3 , @srikanthallu )
- [x] add pretreatment step (removal of divalent ions) to compare against NF as pretreatment (@aladshaw3)
- [x] add reversible pump type ERD to RO (@adam-a-a , @TimBartholomew) 
- [x] Apply eNRTL to compute saturation ratio of gypsum at the RO outlet, considering 5 elements representative of seawater (@andrewlee94) 
- [x] Compute saturation ratio of gypsum at the membrane interface (currently computed at bulk)
- [x] get cost data for NF, lime/soda ash addition in chemical pretreatment step, and chlorination in posttreatment step(@adam-a-a)
- [x] improve model stability where needed (@bknueven)
- [ ] results/visualization via parameter sweep, etc. (@eyoung55, @jefalon) 

**Nice to have, but not required for the MVP:** 
- [ ] Make separate RO model compatible with general property model to enable computation of osmotic pressure via eNRTL (@adam-a-a)
- [ ] Integration of other chemical processes: re-carbonization/pH control in post-treatment
- [ ] add isobaric ERD with booster pump
- [x] add multiple stages of RO (added two stage RO)
