### ISSUE TITLE
Master issue for Electrolyte DB v2

### ISSUE THREAD

**Issue by dangunter** [nawi-hub/proteuslib#49]
In v2, we will support a simple interface to possible diverse backends, starting with something simple.

- [x] Port over data from workspace
- [x] Write a JSON schema for it
- [x] Write a data reader and validator with JSON schema
- [x] Load data into MongoDB
- [x] Add functions for simple search in that DB
- [x] Replace existing "stitch dictionaries" functions with search/retrieve from the database

**Comment by dangunter** [comment]
All done with this list of to-dos
